name: test

on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure
      uses: ./.github
      with:
        builddir: build
    - name: Run test
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        cd build && 
        make check
