name: test

on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure
      uses: ./.github
      with:
        builddir: build
    - name: Run test
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        cd build && 
        make check
  asan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure
      uses: ./.github
      with:
        builddir: build
        CFLAGS: '-fsanitize=address -fno-omit-frame-pointer -g -Wall'
        LDFLAGS: '-fsanitize=address'
    - name: Run test
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        cd build &&
        export ASAN_OPTIONS="abort_on_error=1" &&
        make check
